baseURL: https://www.blazorserver.com
theme: hugobricks
defaultContentLanguage: en
assetDir: static

markup:
  goldmark:
    renderer:
      unsafe: true
    extensions:
      extras:
        insert:
          enable: true
        mark:
          enable: true
        subscript:
          enable: true
        superscript:
          enable: true

languages:
  en:
    languageName: English
    contentDir: content/en
    weight: 1
    disabled: false
    permalinks:
      page:
        projects: /projects/:slug
        showcases: /showcases/:slug
      section:
        projects: /projects/
        showcases: /showcases/

  cn:
    languageName: 中文
    contentDir: content/cn
    weight: 2
    disabled: false
    permalinks:
      page:
        projects: /projects/:slug
        showcases: /showcases/:slug
      section:
        projects: /projects/
        showcases: /showcases/
     